apiVersion: v1
kind: Service
metadata:
  name: {{ include "clickhouse.fullname" . }}-http
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.httpPort | default 8123 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "clickhouse.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "clickhouse.fullname" . }}-client
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.clientPort | default 9000 }}
      targetPort: client
      protocol: TCP
      name: client
  selector:
    {{- include "clickhouse.selectorLabels" . | nindent 4 }}